### ISSUE TITLE
Add support for asynchronous checks

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-health#100] opened 2020-05-27 06:19 UTC
The current approach only supports synchronous checks which discard the usage of reactive components such as reactive database client. While the user could block, it's a reactive antipattern. Typically, it leads to such kind of [discussion](https://stackoverflow.com/questions/61530354/quarkus-healthcheck).

I would like to discuss the possibility to introduce asynchronous checks defined as follows:

```
public interface AsyncCheck {

    public Uni<HealthCheckResponse> call();

}
```

This would ease the integration of reactive component with the health check support.

Another discussion would be to use an async-first approach (don't scream :-)), which would avoid the sequential chain to the current architecture and allows executing the different checks concurrently and join the results. It would make simpler the implementation of a fail-fast mode (as soon as one check fails, fail even if other checks are not yet completed) or "wait for all" mode (wait for the completion or timeout of all the checks before returning the answer). Note that the fail-fast feature would introduce a new "state" being "unknown" if the result has not been retrieved before the first failure. 

Potentially, the `@Blocking` annotation can be used as an indicator of a method for implementations to know how to handle blocking properly. (from #93)

**Comment by cescoffier** [comment] 2020-05-27 06:19
CC @kenfinnigan

**Comment by xstefank** [comment] 2020-05-27 06:21
@cescoffier not a duplicate of https://github.com/smallrye/smallrye-health/issues/93? BTW, this is definitely something I would like to include.

**Comment by cescoffier** [comment] 2020-05-27 06:24
@xstefank Thanks! Yes it does. My description gives a bit more details. I will edit it to include Ken's comments.

**Comment by kenfinnigan** [comment] 2020-05-27 17:21
Adding my comment from the other issue:

Currently it's very messy to get a health check to execute in an asynchronous manner. See https://stackoverflow.com/questions/61530354/quarkus-healthcheck

It would be better to have built-in support for asynchronous execution.

Possibly consider the use of `@Blocking` as an indicator on the method for implementations to know how to handle it.

**Closed** 2020-06-19 07:27 UTC
